apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: sakshi19091998/database:50
        ports:
        - containerPort: 18082
        - containerPort: 18083
        - containerPort: 18084
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  type: NodePort
  ports:
  - protocol: TCP
    port: 18084           # Port the service exposes
    targetPort: 18084     # Port in the container
    nodePort: 30084       # Port on the node (accessible via localhost)
