apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  path: finos-traderX/apps/blue/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
  validation: client
