apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: flux-system
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database-app
        image: kirtigupta1234/github-flux-database:latest-1746793385
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 18082
            protocol: TCP
          - containerPort: 18083
            protocol: TCP
          - containerPort: 18084
            protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - name: "18082"
      port: 18082
      targetPort: 18082
    - name: "18083"
      port: 18083
      targetPort: 18083
    - name: "18084"
      port: 18084
      targetPort: 18084

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traderx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
        - path: /account-service(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: account-service
              port:
                number: 8080
        - path: /db-web(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: database
              port:
                number: 18084
        - path: /ng-cli-ws
          pathType: Prefix
          backend:
            service:
              name: web-front-end-angular
              port:
                number: 8080
        - path: /people-service(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: people-service
              port:
                number: 8080
        - path: /position-service(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: position-service
              port:
                number: 8080
        - path: /reference-data(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: reference-data
              port:
                number: 8080
        - path: /socket.io/
          pathType: Prefix
          backend:
            service:
              name: trade-feed
              port:
                number: 8080
        - path: /trade-feed(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: trade-feed
              port:
                number: 8080
        - path: /trade-service(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: trade-service
              port:
                number: 8080
        - path: /trade-processor(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: trade-processor
              port:
                number: 8080
        - path: /traderx(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: web-front-end-angular
              port:
                number: 8080
