apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: database-app
          image: kirtigupta1234/github-flux-database:blue-tag
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
    version: blue
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: database-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /db-web(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: database
                port:
                  number: 18084
