name: Infrastructure Provisioning
on: 
  workflow_dispatch:

env:
  AWS_REGION: us-east-1  
  INSTANCE_TYPE: t3.medium
  AMI_ID: ami-0c02fb55956c7d316
  KEY_NAME: PrometheusKey
  SECURITY_GROUP_ID: sg-06eff5f4c6f6e5e10
  SUBNET_ID: subnet-068c08d255894fbae

jobs:
  provision-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Launch EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id $AMI_ID \
            --instance-type $INSTANCE_TYPE \
            --key-name $KEY_NAME \
            --security-group-ids $SECURITY_GROUP_ID \
            --subnet-id $SUBNET_ID \
            --count 1 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=GitHubActions-EC2}]'
