name: InputsCheck

on:
  workflow_dispatch:
    inputs:
      services:
        description: "Enter service name"
        type: string
        default: service1

jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: |
          echo "Hello"
