name: CI Pipeline

on: push

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Match with your .nvmrc or package.json engines

      - name: Install dependencies
        run: npm install
        working-directory: ./web-front-end/angular

      - name: Run Linter
        run: ng lint
        working-directory: ./web-front-end/angular