name: Build Java Application using Gradle

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java (Java 17 in this example, but you can adjust)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Use 'temurin' for newer versions of JDK

    # Step 3: Cache Gradle dependencies (optional but speeds up builds)
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Step 4: Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew build

    # Step 5: Run tests (if you have tests defined)
    - name: Run tests with Gradle
      run: ./gradlew test